### ISSUE TITLE
User_id on Account and DepositAccount differ

### ISSUE THREAD

**Issue by Xypus** [rentshare/rentshare-ruby#2]
Having created an Account with a DepositAccount tied to it:

```
RentShare::Account.create(
        email: email,
        full_name: "#{first_name} #{last_name}",
        company: company,
        phone: phone_number,
        user_type: 'recipient',
        deposit_accounts:
          [
            RentShare::DepositAccount.new(
              company: company,
              phone: phone_number,
              address:
                RentShare::Address.new(
                  street_address: address_line_1,
                  city_state_zip: "#{city}, #{state} #{postal_code}"
                )
            )
          ]
      )
```

The resulting Account object has different `user_id` than its DepositAccount, making it impossible to tie one to another.

The resulting Account object does not respond to `deposit_accounts` method:

```
 acc.deposit_accounts
NoMethodError: undefined method `deposit_accounts' for #<RentShare::Account:0x00000005f6d330>
from /bundle/bundler/gems/rentshare-ruby-89531ca88962/lib/rentshare/api_resource.rb:96:in `method_missing'
```

The following line from the [documentation](https://rentshare-api-docs-dev.herokuapp.com/?ruby#javascript-callbacks21):
```
data-deposit-account-id: Specify the deposit account id. Not required for accounts with only one deposit account.
```
leads me to believe that the `default` attribute on the deposit account should be set to `true` if it's the only one, however in my case it is set to `false`. 

As I'm using the `persisted accounts` approach I need to create both accounts in one go and be able to update them both in case the user wants to change any attributes.

**Comment by ianhalpern** [comment]
## User id not matching
User id's are deprecated in this latest api version. We released an update to remove the user ids from the response.

## Account object missing deposit_accounts method
For the moment, deposit accounts need to be explicitly specified as a return field, so you need `fields: '*,deposit_accounts'`. We are working on making it the default for recipient user-types.
Try:
```ruby
RentShare::Account.create(
        email: email,
        full_name: "#{first_name} #{last_name}",
        company: company,
        phone: phone_number,
        user_type: 'recipient',
        deposit_accounts:
          [
            RentShare::DepositAccount.new(
              company: company,
              phone: phone_number,
              address:
                RentShare::Address.new(
                  street_address: address_line_1,
                  city_state_zip: "#{city}, #{state} #{postal_code}"
                )
            )
          ],
          fields: '*,deposit_accounts'
      )
```

Alternatively, you don't need to use a separate account for each deposit account if you don't want to. For example:

```ruby
RentShare::DepositAccount.create(
      company: company,
      phone: phone_number,
      address: RentShare::Address.new(
            street_address: address_line_1,
            city_state_zip: "#{city}, #{state} #{postal_code}"
       )
)
```

This would associate the deposit account with your main account.

## Default flag

The default flag is also being deprecated so you can just ignore this as well.

**Comment by Xypus** [comment]
@ianhalpern 
```For the moment, deposit accounts need to be explicitly specified as a return field, so you need fields: '*,deposit_accounts'.```

I cannot find any mention of `return fields` that need to be explicitly specified anywhere in the API docs. How does it exactly work? Does `'*,deposit_accounts'` mean `all default fields plus deposit_accounts`? If so, how do I know which fields are default and which are not? When do the specified fields need to be specified - while creating a resource or can I update it later?

**Comment by Xypus** [comment]
@ianhalpern 
When I specify deposit accounts as a return field in `RentShare::Account.create` method it does return the newly created account with its deposit accounts. However single query does not accept the `fields` keyword:
```
RentShare::Account.get('account_id', fields: '*,deposit_accounts')
=> ArgumentError: unknown keyword: fields
```
 and a bulk query seems to lose the deposit account:
```
acc = RentShare::Account.select(id: 'account_id', fields: '*,deposit_accounts').first
acc.deposit_accounts
=> []
```
I need to be able to retrieve the deposit account of an account at any time, not only as a `create` method response.

**Comment by ianhalpern** [comment]
The return fields parameter is only briefly mentioned in the **Special Fields** sub-section on the [query language](https://developer.rentshare.com/#query-language) section. You're exactly correct on the meaning, `*` means all default fields, and any additional fields afterwards are extra non-default fields.

You don't need to specify them on create initially, you can specify in any additional get or update request later but for the most part these are never used. This is just a special case for a work-around while we work on the ticket to make `deposit_accounts` a default field for `recipient` user-types. Since the current intent is that non-default fields aren't supposed to be used generally, we aren't including them in the documentation.

We just released an update to the ruby gem to allow the fields argument for the get call:
```ruby
RentShare::Account.get('account_id', fields: '*,deposit_accounts')
```
Also, the bulk query should now return the `deposit_accounts` list.
