### ISSUE TITLE
Address queries not working

### ISSUE THREAD

**Issue by Xypus** [rentshare/rentshare-ruby#3]
Having created a DepositAccount with an embedded Address I can retrieve the address by retrieving the account:
```ruby
dep = RentShare::DepositAccount.get('deposit_account_id)
address = dep.address
address_id = address.id
```
However a direct querying `RentShare::Address.get(address_id)` returns `RentShare::NotFound`. I get the same error when bulk querying for all Address objects: `RentShare::Address.select()`.

**Comment by ianhalpern** [comment]
The address endpoint has been fully exposed in the api now so you should be able to query it directly.
