### ISSUE TITLE
Address embedded update not working

### ISSUE THREAD

**Issue by Xypus** [rentshare/rentshare-ruby#4]
Updating an account as follows:

```ruby
rentshare_account.update(
      email: 'some_email',
      deposit_accounts:
        [
          {
            id: deposit_account.id,
            company: 'Changed Company',
            address:
              {
                id: address.id,
                street_address: '1 New Street' 
              }
          }
        ]
    )
```

returns `RentShare::InternalError`. Removing the Address object from the update makes it work so this is probably the culprit (see also [Address queries not working](https://github.com/rentshare/rentshare-ruby/issues/3) issue).

**Comment by ianhalpern** [comment]
The problem should be fixed now but let me know if you are still having issues.
